weekend:
  - 6
  - 7

classes:
  - 
    name: 'english'
    classroom: 'A313'
    teacher: 'not platt'
  - 
    name: 'math'
    classroom: 'A513'
    teacher: 'platt'

timetable:
  - ['english', 'math', 'english', 'math']
  - ['math', 'math', 'math', 'math']
