weekend:
  - 6
  - 7

classes:
  - 
    name: 'english'
    classroom: 'A313'
    teacher: 'not platt'
  - 
    name: 'math'
    classroom: 'A513'
    teacher: 'platt'

timetable:
  day1: ['english', 'math']
